name: CI

on: push

jobs:
  check:
    runs-on: ubuntu-latest
    container: keberson/vk-gcc
    steps:
      - uses: actions/checkout@v2 
      - run: python3 cpplint.py --extensions=cpp src/*.cpp include/*.h tests/*.cpp
      - run: cppcheck --error-exitcode=1 --enable=all --suppress=missingIncludeSystem src/ tests/ -I include/
  build:
    runs-on: ubuntu-latest
    container: keberson/vk-gcc
    needs: [check]
    steps:
    - uses: actions/checkout@v2 
    - run: cmake .
    - run: make
    - run: ls
    - name: Upload matrix
      uses: actions/upload-artifact@v2
      with:
        name: matrix
        path: matrix_calculator_test
    - name: Upload vector
      uses: actions/upload-artifact@v2
      with:
        name: vector
        path: vector_test
  test:
    runs-on: ubuntu-latest
    container: keberson/vk-gcc
    needs: [build]
    steps:
      - name: Download matrix
        uses: actions/download-artifact@v2
      - name: Run matrix
        shell: bash
        run: |
          ls
          ./matrix_calculator_test
