name: CI

on: push

jobs:
  check:
    runs-on: ubuntu-latest
    container: keberson/vk-gcc
    steps:
      - uses: actions/checkout@v2
      - run: python3 cpplint.py --extensions=cpp src/*.cpp include/*.h tests/*.cpp
      - run: cppcheck --error-exitcode=1 --enable=all --suppress=missingIncludeSystem src/ tests/ -I include/
  build:
    runs-on: ubuntu-latest
    container: keberson/vk-gcc
    needs: [check]
    steps:
      - uses: actions/checkout@v2
      - run: cmake .
      - run: make
      - run: ls
      - name: Upload set
        uses: actions/upload-artifact@v2
        with:
          name: set
          path: test_set
      - name: Upload set library
        uses: actions/upload-artifact@v2
        with:
          path: libset.so
  test:
    runs-on: ubuntu-latest
    container: keberson/vk-gcc
    needs: [build]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
      - name: Run tests
        shell: bash
        run: |
          mv artifact/* .
          chmod u+x set/test_set
          ./set/test_set