name: CI

on: push

jobs:
  check:
    runs-on: ubuntu-latest
    container: keberson/vk-gcc
    steps:
      - uses: actions/checkout@v2 
      - run: python3 cpplint.py --extensions=cpp src/*.cpp
      - run: cppcheck --enable=all --suppress=missingIncludeSystem .
  build:
    runs-on: ubuntu-latest
    container: keberson/vk-gcc
    needs: [check]
    steps:
    - uses: actions/checkout@v2 
    - run: make build
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        path: matrix_calculator_test
  test:
    runs-on: ubuntu-latest
    container: keberson/vk-gcc
    needs: [build]
    steps:
      - uses: actions/checkout@v2 
      - run: cmake . &&  cmake --build . &&  CTEST_OUTPUT_ON_FAILURE=TRUE cmake --build . --target test
